# Generated by Django 5.1.3 on 2025-12-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_code', models.CharField(max_length=10, unique=True)),
                ('bank_name', models.CharField(max_length=150)),
                ('branch_name', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'LC_BANK_MASTER',
            },
        ),
        migrations.CreateModel(
            name='LCDocumentTypeMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_code', models.CharField(max_length=10, unique=True)),
                ('doc_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'LC_DOCUMENT_TYPE_MASTER',
            },
        ),
        migrations.CreateModel(
            name='PartyMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('party_code', models.CharField(max_length=20, unique=True)),
                ('party_name', models.CharField(max_length=200)),
                ('party_type', models.CharField(help_text='e.g. Applicant, Beneficiary, Buyer, Seller', max_length=30)),
                ('address_line1', models.CharField(blank=True, max_length=200, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'LC_PARTY_MASTER',
            },
        ),
        migrations.CreateModel(
            name='PlantMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plant_code', models.CharField(max_length=10, unique=True)),
                ('plant_name', models.CharField(max_length=150)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'LC_PLANT_MASTER',
            },
        ),
    ]
