"""
Django settings for vendorproject project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9t25jai&9k2k_6-%ueo+4iv_hwblwqw(s4_5$^a3%iv67__8af'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# Application definition

DEPENDENCY_APPS = [
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    #'rest_framework_swagger',
    'reversion',
    'multiselectfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    #'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'rbac',       
    'workflow',
    'api',
    'vendorproject',
    
]
PROJECT_APPS = [
    'employee_separation',
]

INSTALLED_APPS = DEPENDENCY_APPS + PROJECT_APPS

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  
]


ROOT_URLCONF = 'vendorproject.urls'
APPEND_SLASH = True


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vendorproject.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'e_separation_db',
        'USER': 'postgres',
        'PASSWORD': 'Test@12345',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}



REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],

    # DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.IsAuthenticated',  
    # ]

    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser'
    ],

    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
    ],
    'DEFAULT_METADATA_CLASS': 'api.metadata.MinimalMetadata',

    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema'
}

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
ALLOWED_HOSTS = ['*']
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    

    
]

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "req",
    "source",
    "approval-authorization",
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATICFILES_STORAGE = (
    'whitenoise.storage.CompressedManifestStaticFilesStorage'
)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
LOGIN_REDIRECT_URL = '/admin/'

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = ('')
EMAIL_PORT = ('')
EMAIL_USE_TLS = ('')
EMAIL_HOST_USER = ('')
EMAIL_HOST_PASSWORD = ('')

WORKFLOW_MAIL_MAP = {}
MODELS_WITH_MAIL_APPROVAL = []
LANDING_PAGE_FMT = "http://localhost:3000/app/ApprovalForm/{}"
APPROVAL_GROUPS = {}
WORKFLOW_EMAIL_CONFIGS = {}
WORKFLOW_MODEL_LIST = []
APPROVAL_API_URLS = {}


MASTERS_APP_RBAC = 'masters'
MODEL_FIELD_CHOICES = []
DATA_RESTRICT_PERMISSIONS = {}

USER_PROFILE_MODEL_DETAILS = {
    'app': 'rbac',
    'model': 'AUth',
    'search_on_field': ''
}


MASTER_FILES_MOSS_UPLOAD = False
MOSS_BASE_URL = ''
MOSS_USERNAME = ''
MOSS_PASSWORD = ''
RELATIVE_FOLDER_TO_UPLOAD_URL = ''


MASTERS_APP_NAME = 'masters'
DATE_INPUT_FORMAT = []
DATE_TIME_INPUT_FORMAT = ["iso-8601"]
TIME_INPUT_FORMAT = []


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
X_FRAME_OPTIONS = ''
APP_NAME = ()
ENVIRONMENT = ()

GROUP_WISE_STATUS_MAPPING = {}
    # 'HR': ['Pending For Approval', 'Initiated', 'Approved'],

APPLY_SEARCH_MODEL_FIELDS = {
    'bank_master': ['bank_code','bank_name','branch_name','city','swift_code'],
    'plant_master': ['plant_code','plant_name','city', 'country'],
    'party_master': ['party_code','party_name','party_type','address_line1','city', 'country'],
    'lc_document_type': ['doc_code','doc_name','description',],
}

FOREIGN_KEY_UI_NAME_MAP = {}

EXCEL_EXPORT_CONFIGS = {}

RABBITMQ_CONF = {
    "RABBITMQ_CON_URL": "",
    "RABBITMQ_QUEUE": "",
    "SENDER_MAIL": "",
    "MAIL_CREDENTIALS": {"sender_email": "", "mailserver": ""}}

MODEL_VALIDATORS = {}
POST_SAVE_OBJ_RETURN_HOOKS = {}

EXCEL_IMPORT_CONFIGS = {}

TRANS_FILTER_QS_SERIALIZER = []

DISPLAY_MODELS = {
    'bank_master': 'Bank Master',
    'plant_master': 'Plant Master',
    'party_master': 'Party Master',
    'lc_document_type': 'LC Document Type',}

EXTRA_USER_META = {
    'MASTERS': [
        {
            'app': 'employee_separation',
            'title': 'Master Data',
        }
    ],
    'Master Screens': [
        {
            'screen': 'BankMaster',
            'type': 'subsection',
            'title': 'Bank Master'
        },
        {
            'screen': 'PartyMaster',
            'type': 'subsection',
            'title': 'Party Master'
        },
        {
            'screen': 'PlantMaster',
            'type': 'subsection',
            'title': 'Plant Master'
        },
        {
            'screen': 'LCDocumentTypeMaster',
            'type': 'subsection',
            'title': 'LC Document Type Master'
        }
    ]
}

SECTION_ICONS = {
    'MASTERS': 'fa fa-th-list',
    'GENERAL': 'fa fa-dashboard',}

URL_METADATA_CLASS = {
    'api': 'api.metadata.ApiMetadata',
    'User': 'rbac.metadata.RbacMetadata',
    'Suggest': 'rbac.metadata.RbacMetadata',
    'Group': 'rbac.metadata.RbacMetadata',
    'Permission': 'rbac.metadata.RbacMetadata',}

AUTO_GENERATION_SECTIONS = ['MASTERS']

DISPLAY_MODEL_FIELDS = {
    
    "bankmaster": ["id", "bank_code", "bank_name", "city", "swift_code"],
    "partymaster": ["id", "party_code", "party_name", "party_type", "city", "country"],
    "lcdocumenttypemaster": ["id", "doc_code", "doc_name", "description"],
    "plantmaster": ["id", "plant_code", "plant_name", "city", "country"],}


CHECK_USER_REGISTRATION = False

USER_PROFILE_SERIALIZER = ''

WORKFLOW_EMAIL_POLICY = {
    'default': {
        'Init': {
            'request': 'workflow.email_policy.notify_next_level',
        },
        'Approve': {
            'request': 'workflow.email_policy.notify_next_level',
            'notification': 'workflow.email_policy.get_request_initiator'
        },
        'Reject': {
            'notification': 'workflow.email_policy.notify_the_hierarchy'
        },
    }
}
















